title: ELD based console app
description: Codes, equations and algorithms for economic load dispatch in power systems.

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-include-cache

relative_links:
  enabled: true
  collections: true
include:
 - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

remote_theme: pages-themes/dinky

mermaid:
  version: 11.4.1

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

mathjax:
  enable: true
  use_preview: true
